### ISSUE TITLE
Problems installing on windows

### ISSUE THREAD

**Issue by sblunt** [willvousden/ptemcee#11]
I've tried installing `ptemcee` on three windows computers, and I get the same error on all of them:

`
Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "C:\Users\Rajeev\AppData\Local\Temp\pip-install-3exhreqn\ptemcee\setup.py", line 39, in <module>
       long_description=read('README.rst'),
     File "C:\Users\Rajeev\AppData\Local\Temp\pip-install-3exhreqn\ptemcee\setup.py", line 20, in read
       return f.read()
     File "C:\Users\Rajeev\Miniconda3\lib\encodings\cp1252.py", line 23, in decode
       return codecs.charmap_decode(input,self.errors,decoding_table)[0]
   UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 449: character maps to <undefined>
`

As far as I can tell, there's at least one non-ASCII character in the README that's preventing install. Cloning the repo and removing the README fixes the issue.

**Comment by amyharris2** [comment]
Hi,

I assume you're using Python version 3. In which case, I think the problem is in line 18 in setup.py:
kwargs = {'encoding': 'utf-8'} if major > 3 else {}

The problem is it only sets the encoding if the major version is > 3, whereas it needs to be >= 3. So change the line to the following, and it should work. 
kwargs = {'encoding': 'utf-8'} if major >= 3 else {}

:)

**Comment by sblunt** [comment]
Yes, I've gotten it to work on my own machines, but since this package is a dependency for my own package, I would love if users could just pip install it themselves without complication.

**Comment by RiccardoBuscicchio** [comment]
Hello, given ptemcee is a requirement of other pip packages, would you please update it on PyPi as well? I got recently the same error, because the [pypi setup.py file](https://pypi.org/project/ptemcee/1.0.0/#files) still have the same typo.

**Comment by Jetzang** [comment]
Trying to install via ligo.skymap and receiving the following errors:

File "<string>", line 1, in <module>
      File "C:\Users\xxxxx\AppData\Local\Temp\pip-install-xvptqw8g\ptemcee\setup.py", line 39, in <module>
        long_description=read('README.rst'),
      File "C:\Users\xxxxx\AppData\Local\Temp\pip-install-xvptqw8g\ptemcee\setup.py", line 20, in read
        return f.read()
      File "c:\users\xxxxx\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]

Seems like a similar issue in setup.py as above?

**Comment by Steelhead86** [comment]
When attempting to install via pip3 on Windows 10:

`C:\Users\*****>pip3 install ptemcee
Collecting ptemcee
  Using cached ptemcee-1.0.0.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\*****\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\*****\\AppData\\Local\\Temp\\pip-install-bn2fi2tv\\ptemcee\\setup.py'"'"'; __file__='"'"'C:\\Users\\*****\\AppData\\Local\\Temp\\pip-install-bn2fi2tv\\ptemcee\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\*****\AppData\Local\Temp\pip-pip-egg-info-82opejqy'
         cwd: C:\Users\*****\AppData\Local\Temp\pip-install-bn2fi2tv\ptemcee\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\*****\AppData\Local\Temp\pip-install-bn2fi2tv\ptemcee\setup.py", line 39, in <module>
        long_description=read('README.rst'),
      File "C:\Users\*****\AppData\Local\Temp\pip-install-bn2fi2tv\ptemcee\setup.py", line 20, in read
        return f.read()
      File "c:\users\*****\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 449: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

This appears to be the same issue as elsewhere in this thread. Are there existing workarounds?
